name: CI
on:
  pull_request:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Yarn cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('.yarnrc.yml') }}

      - name: Install dependencies
        run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Check TypeScript
        run: yarn type-check

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn eslint . --ext .ts  --max-warnings 0 # no fix

      - name: Test
        run: yarn test

      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
